# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170721_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_certified',
            field=models.BooleanField(default=False, verbose_name='인증여부'),
            preserve_default=False,
        ),
    ]
