# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_certified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_certified',
            field=models.DateTimeField(blank=True, verbose_name='인증시간'),
        ),
    ]
